version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'digitalhouse-dev'
      MYSQL_USER: 'usr-digitalhouse'
      MYSQL_PASSWORD: 'pwd-digitalhouse'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'inscription-dev-mongo'
      MONGO_INITDB_ROOT_USERNAME: 'usr-inscription-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-inscription-mongo'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro